Completed react-accordion-component.
stefancarrera/rc0521-code-solutions pull request #126
Opened 2021-07-13 20:19 UTC by stefancarrera

![react-accordion](https://user-images.githubusercontent.com/53131688/125519204-c32f964f-e7c0-43ec-b156-0c5548d934a3.gif)

2021-07-13 20:31 UTC, scbowler requested changes
Good job getting it to work, but we want to make our accordion reusable so any properly formatted topic data passed in via props should work, not just specific data. Below are comments that will help guide you on making it dynamic. Let me know if you have any questions on any of this!

2021-07-13 20:31 UTC, scbowler commented on react-accordion-component/src/index.jsx
> +
The topics data should be defined here in an array, something like:

```JAVASCRIPT
const topics = [
  {
    id: 1,
    title: 'HTML',
    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia corporis eum ad illo error ex dolorem facilis harum cum excepturi!'
  },
  {
    id: 2,
    title: 'JavaScript',
    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia corporis eum ad illo error ex dolorem facilis harum cum excepturi!'
  },
  {
    id: 3,
    title: 'CSS',
    content: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia corporis eum ad illo error ex dolorem facilis harum cum excepturi!'
  }
];
```

2021-07-13 20:31 UTC, scbowler commented on react-accordion-component/src/index.jsx
> +  <Accordion />,
Here you want to pass in your topic data via props:

```JSX
<Accordion topics={topics} />
```

2021-07-13 20:31 UTC, scbowler commented on react-accordion-component/src/accordion.jsx
> +      ]
Your component should work with any topic data passed in, not just this exact set of data. The only thing you need in state is to track the `id` of which item should be open.

```JAVASCRIPT
this.state = {
  openId: null
};
```

2021-07-13 20:31 UTC, scbowler commented on react-accordion-component/src/accordion.jsx
> +    }
Again here this is too specific, should work with any data set. Handle click just needs to set the openId in state.

```JAVASCRIPT
handleClick(id) {
  this.setState({ openId: id });
}
```

2021-07-13 20:31 UTC, scbowler commented on react-accordion-component/src/accordion.jsx
> +  }
Shouldn't need individual methods for specific topics

2021-07-13 20:31 UTC, scbowler commented on react-accordion-component/src/accordion.jsx
> +      </div>
Here you should be mapping over your data to generate your JSX. It would look something like:

```JSX
<div className="accordion">
    {
      this.props.topics.map(item => (
        <div className="accordion-item" onClick={() => this.setOpenId(item.id)}>
          <h1 className="accordion-title">{item.title}</h1>
          <div className={`accordion-content ${this.state.openId === item.id ? 'show' : 'hide'}`}>
            {item.content}
          </div>
        </div>
      ))
    }
</div>
```

Your classNames, variable names, method names may vary but this is the overall concept of how to make it dynamic.

2021-07-13 23:35 UTC, scbowler requested changes
Let me know if you have any questions on finishing this.

2021-07-13 23:35 UTC, scbowler commented on react-accordion-component/src/accordion.jsx
> +    );
Looks like on the right track but incomplete

2021-07-13 23:39 UTC, stefancarrera commented on react-accordion-component/src/accordion.jsx
> +    );
I had to commit before I could start on the new express assignment

2021-07-14 13:44 UTC, stefancarrera commented
![react-accordion](https://user-images.githubusercontent.com/53131688/125632631-e18cd58e-f862-46ff-b811-f80dbfd5eb34.gif)

2021-07-14 17:41 UTC, scbowler approved these changes
Great job implementing the feedback! Looks good! 👍

2021-07-14 18:32 UTC, merged