Completed fetch-in-react-practice.
stefancarrera/rc0521-code-solutions pull request #130
Opened 2021-07-14 23:34 UTC by stefancarrera

![react-practice](https://user-images.githubusercontent.com/53131688/125705794-2aabbe2c-bc1d-45b3-b850-6ce29f9ba01f.gif)

2021-07-14 23:40 UTC, scbowler requested changes
Looking good! But one update needed

2021-07-14 23:40 UTC, scbowler commented on fetch-in-react-practice/client/components/app.jsx
> +        updatedTodos[item.id] = item;
This mutates the state, you need to make a new array before you can make changes to it. You can do the following to make a new array:

```JAVASCRIPT
const updatedTodos = this.state.todos.slice();
updatedTodos[item.id] = item;
```

2021-07-14 23:51 UTC, stefancarrera commented
Corrected the original state mutation from the toggleCompleted function

2021-07-15 00:35 UTC, scbowler approved these changes
Looks good! 👍

2021-07-15 00:36 UTC, merged